languageCode = "en-us"
title = "Africa-Imali"
baseURL = "africaimali.com"
theme = "massively"
googleanalytics = "UA-113904582-3"
disqusShortname = "hugo-massively"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
  title = "Africa Imali - English"
[languages.af]
  languageName = "Afrikaans"
  title = "Africa Imali - Afrikaans"
[languages.xo]
  languageName = "Xhosa"
  title = "Africa Imali - Xhosa"
[languages.zu]
  languageName = "Zulu"
  title = "Africa Imali - Zulu"
[languages.es]
  languageName = "Español"
  title = "Africa Imali - Español"
[languages.fr]
  languageName = "Français"
  title = "Africa Imali - Française"
